Fix MSYS2+Clang build
aom_dsp/psnrhvs.c:30:3: error: call to undeclared function 'aom_fdct8x8'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
aom_dsp/psnrhvs.c:41:3: error: call to undeclared function 'aom_highbd_fdct8x8'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

In other hand see aom_dsp/aom_dsp_rtcd_defs.pl:

    if (aom_config("CONFIG_INTERNAL_STATS") eq "yes"){
      # 8x8 DCT transform for psnr-hvs. Unlike other transforms isn't compatible
      # with av1 scan orders, because it does two transposes.
      add_proto qw/void aom_fdct8x8/, "const int16_t *input, tran_low_t *output, int stride";
      specialize qw/aom_fdct8x8 neon sse2/, "$ssse3_x86_64";
      # High bit depth
      if (aom_config("CONFIG_AV1_HIGHBITDEPTH") eq "yes") {
        add_proto qw/void aom_highbd_fdct8x8/, "const int16_t *input, tran_low_t *output, int stride";
        specialize qw/aom_highbd_fdct8x8 sse2/;
      }
    }

So add -DCONFIG_INTERNAL_STATS=1 and -DCONFIG_AV1_HIGHBITDEPTH=1 to CMake args as workaround